### ISSUE TITLE
Enabling `location overlay` in DF crashes game

### ISSUE THREAD

**Issue by Severnarch** [CodeUtilities/CodeUtilities-2.0#89]

**Comment by Reasonlesss** [comment]
Can you provide more info

**Comment by Severnarch** [comment]
> Can you provide more info

When in DiamondFire, head to CodeUtilities settings then click on the Location Overlay setting, it immediately says Saving game... and closes Minecraft.

**Comment by TechStreetDev** [comment]
I think reason isn’t talking about a crash log

**Comment by Severnarch** [comment]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/12/2021, 11:11
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: com/sun/javafx/application/PlatformImpl
	at io.github.codeutilities.mod.features.AudioHandler.load(AudioHandler.java:45)
	at io.github.codeutilities.CodeInitializer.addIf(CodeInitializer.java:36)
	at io.github.codeutilities.mod.config.types.BooleanSetting.setValue(BooleanSetting.java:22)
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.save(BooleanListEntry.java:89)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.shedaniel.clothconfig2.gui.entries.SubCategoryListEntry.save(SubCategoryListEntry.java:197)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:196)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.saveAll(ClothConfigScreen.java:144)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.lambda$init$3(ClothConfigScreen.java:158)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:290)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:111)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
	at net.minecraft.class_1041.method_15998(class_1041.java:398)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.application.PlatformImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 43 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.codeutilities.mod.features.AudioHandler.load(AudioHandler.java:45)
	at io.github.codeutilities.CodeInitializer.addIf(CodeInitializer.java:36)
	at io.github.codeutilities.mod.config.types.BooleanSetting.setValue(BooleanSetting.java:22)
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.save(BooleanListEntry.java:89)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.shedaniel.clothconfig2.gui.entries.SubCategoryListEntry.save(SubCategoryListEntry.java:197)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:196)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.saveAll(ClothConfigScreen.java:144)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.lambda$init$3(ClothConfigScreen.java:158)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:290)
	at net.minecraft.class_312.method_1611(class_312.java:92)

-- Affected screen --
Details:
	Screen name: me.shedaniel.clothconfig2.gui.ClothConfigScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:111)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)

-- Affected level --
Details:
	All players: 1 total; [class_746['TJ20201'/1188812, l='ClientLevel', x=15547.07, y=50.00, z=2157.23]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1023,54,-1070), Chunk: (at 1,3,2 in -64,-67; contains blocks -1024,0,-1072 to -1009,255,-1057), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Level time: 28312 game time, 6000 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Reasonlesss** [comment]
@Tomoli75 @tk2217 this appears to be a PA issue

**Comment by tk2217** [comment]
Yep that's P: A, I really need to recode the codeutils integration.

**Comment by TechStreetDev** [comment]
We plan to drop CU P:A integration with v2 anyway and make it it’s on mod

**Comment by Severnarch** [comment]
Then why does it only trigger when I enable loc overlay
